ailibaba:
  durid:
    url: jdbc:mysql://192.168.20.89:3306/ziyun?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    maxActive: 20
    maxWait: 10000
    minIdle: 3
    validationQuery: SELECT 'x'
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    borrowConnectionTimeout: 30000

spring:
  redis:
    host: 192.168.20.165
    password: rootpass
    timeout: 3000
    port: 6379
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  freemarker:
    request-context-attribute: request
    content-type: text/html;charset=utf-8
    suffix: .ftl  #坑

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hxzy.entity
  config-location: classpath:mybatis-config.xml

logging:
  file: ./log/mylog.log
  level:
    com.hxzy: debug
    org.mybatis: debug